### ISSUE TITLE
BUG: When user navigate to private subspace auth error is thrown

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/client-web#7264]
**Describe the bug**

**To Reproduce**

1. Go to https://acc-alkem.io/invitations/dashboard with not GA user
2. Or 
3. Create a private space
4. Navigate to it with a non member - error is thrown: `"message": "Authorization: unable to grant 'read' privilege: lookup Collaboration: fc80a36d-af19-47d7-a920-244585089bc9 user: 0d150d7f-a574-4f97-aee7-00bd948e99d4 on authorization f9cd8f74-b274-4cd9-bd0c-6bd57158e807 of type 'collaboration'",`
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW4xQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ce49e74aaf4d4e17001dc71d7333464a989205f/image.png" alt="image.png" />

**Expected behavior**
User is brought to the read about of the 'last' space/subspace it has read about privilege of.
Error is not thrown.

**Comment by larssondenise** [comment]
difference between: not a member, member, 'potential member/preview mode'

**Comment by larssondenise** [comment]
scenario: denise copies link (to subspace in private space) and shares with jeroen and says become a member here

Page that shares with you: you are accessing something that is part of a private space, go to dashboard / sign in to accept the invitations (different 404 page)

**Comment by larssondenise** [comment]
@DonnaDuiker to share some examples with Jeroen of errors she's seen

**Comment by DonnaDuiker** [comment]
Examples:

1. Unknown user (not logged in), not able to read the Demo Space once created for Suzanne: https://alkem.io/suzannedemospace/dashboard (I cannot see from where they where trying to access this)
2. Unknown user (not logged in) not able to read Space (or Subspace in the Space) of Provincie Zuid-Holland: https://alkem.io/transitie-pzh/dashboard
3. Maloe not able to read the Diyalo Foundation Space and a Subspace in there: https://alkem.io/diyalo/dashboard

**Comment by jeroentskui** [comment]
cannot show the parent space in the error message (confidential info)

**Comment by jeroentskui** [comment]
https://alkem.io/building-alkemio-org/challenges/desijningalkemio-3330

**Comment by SimoneZaza** [comment]
@Comoque1 I think this was fixed with the last release? I can't reproduce

**Comment by Comoque1** [comment]
The issue is still reproducible in the case, when user navigate to private subspace - get back to the space and navigate again to the private subspace.
<img width="1314" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekNYQ1E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c83089768b9da8f9761103f95107093b8c7d2a7d/image.png" alt="image.png" />
